"""Integration of stable residual form with fused kernels and dynamic USRNet PSFs."""
import copy
import json
import sys
import unittest

import torch
from extension_loader import ROOT, load_extension

sys.path.insert(0,str(ROOT))
from models.converse_core import converse2d_reference

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
METRICS = {"forward_cases":0,"gradient_cases":0,"max_forward_error":{}}


def data_for(scale,kb,kc,dtype=torch.float64,h=3,w=4):
    x=torch.randn(2,2,h,w,device=DEVICE,dtype=dtype)
    prior=torch.randn(2,2,h*scale,w*scale,device=DEVICE,dtype=dtype)
    weight=torch.randn(kb,kc,3,3,device=DEVICE,dtype=dtype).flatten(2).softmax(-1).reshape(kb,kc,3,3)
    bias=torch.randn(1,2,1,1,device=DEVICE,dtype=dtype)
    return x,prior,weight,bias


def dense(data,s,eps):
    x,prior,weight,bias=data
    B,C,H,W=x.shape
    hs,ws=H*s,W*s
    n=hs*ws
    eye=torch.eye(n,device=x.device,dtype=x.dtype)
    basis=eye.reshape(n,hs,ws)
    batches=[]
    for b in range(B):
        channels=[]
        for c in range(C):
            k=weight[b if weight.shape[0]>1 else 0,c if weight.shape[1]>1 else 0]
            blur=sum(k[i,j]*torch.roll(basis,(i-1,j-1),(-2,-1)) for i in range(3) for j in range(3))
            a=blur[:,::s,::s].reshape(n,H*W).T
            lam=torch.sigmoid(bias[0,c,0,0]-9)+eps
            y=torch.linalg.solve(a.T@a+lam*eye,a.T@x[b,c].flatten()+lam*prior[b,c].flatten())
            channels.append(y.reshape(hs,ws))
        batches.append(torch.stack(channels))
    return torch.stack(batches)


class Combined(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        load_extension()
        torch.manual_seed(610)
        torch.backends.cudnn.allow_tf32=False
        torch.backends.cuda.matmul.allow_tf32=False

    def setUp(self):
        torch.ops.converse2d.clear_cache()

    def test_batched_and_broadcast_psfs(self):
        for dtype in (torch.float64,torch.float32):
            for h,w in ((5,6),(6,5)):
                for s in (1,2,3,4):
                    for kb,kc in ((1,1),(1,2),(2,1),(2,2)):
                        data=data_for(s,kb,kc,dtype,h,w)
                        expected=converse2d_reference(*data,s)
                        with torch.no_grad():
                            for variant in ("v2","v6","v7"):
                                actual=torch.ops.converse2d.forward(*data,s,1e-5,variant)
                                tol=2e-10 if dtype==torch.float64 else 5e-5
                                torch.testing.assert_close(actual,expected,atol=tol,rtol=tol)
                                METRICS["forward_cases"]+=1
                                key=f"{dtype}/{variant}"
                                METRICS["max_forward_error"][key]=max(METRICS["max_forward_error"].get(key,0),(actual-expected).abs().max().item())

    def test_dense_and_broadcast_gradients(self):
        for s in (1,2,3):
            for kb,kc in ((1,1),(1,2),(2,1),(2,2)):
                data=tuple(t.requires_grad_() for t in data_for(s,kb,kc))
                expected=dense(data,s,1e-3)
                upstream=torch.randn_like(expected)
                eg=torch.autograd.grad(expected,data,upstream)
                for variant in ("v2","v6","v7"):
                    actual=torch.ops.converse2d.forward(*data,s,1e-3,variant)
                    ag=torch.autograd.grad(actual,data,upstream)
                    torch.testing.assert_close(actual,expected,atol=1e-9,rtol=1e-9)
                    for a,e in zip(ag,eg): torch.testing.assert_close(a,e,atol=2e-8,rtol=2e-8)
                    METRICS["gradient_cases"]+=1

    def test_dynamic_kernel_and_cache(self):
        for kb,kc in ((1,1),(2,2)):
            data=data_for(3,kb,kc)
            with torch.no_grad():
                torch.ops.converse2d.forward(*data,3,1e-3)
                data[2].add_(0.05)
                actual=torch.ops.converse2d.forward(*data,3,1e-3)
                expected=converse2d_reference(*data,3,1e-3)
                torch.testing.assert_close(actual,expected,atol=1e-10,rtol=1e-10)
            for _ in range(2):
                # Kernel generated by a trainable upstream module, not a leaf.
                raw=torch.randn_like(data[2],requires_grad=True)
                kernel=raw.sigmoid()
                out=torch.ops.converse2d.forward(data[0],data[1],kernel,data[3],3,1e-3)
                g=torch.autograd.grad(out.sum(),raw)[0]
                reference=converse2d_reference(data[0],data[1],raw.sigmoid(),data[3],3,1e-3)
                eg=torch.autograd.grad(reference.sum(),raw)[0]
                torch.testing.assert_close(g,eg,atol=1e-9,rtol=1e-9)

    def test_data_net_low_precision_and_padding(self):
        from models.converse_usrnet import ConvReverseDataNet
        for dtype in (torch.float64,torch.float32,torch.float16,torch.bfloat16):
            for s in (1,2,3):
                layer=ConvReverseDataNet(backend="pytorch").to(device=DEVICE,dtype=dtype)
                x=torch.randn(2,64,5,7,device=DEVICE,dtype=dtype,requires_grad=True)
                k=torch.rand(2,64,3,3,device=DEVICE,dtype=dtype,requires_grad=True)
                expected=layer(x,k,s,padding=1)
                eg=torch.autograd.grad(expected.float().square().mean(),(x,k,layer.alpha))
                if DEVICE=="cuda": layer.backend="cuda"
                actual=layer(x,k,s,padding=1)
                ag=torch.autograd.grad(actual.float().square().mean(),(x,k,layer.alpha))
                tol={torch.float64:1e-10,torch.float32:3e-5,torch.float16:0.008,torch.bfloat16:0.06}[dtype]
                torch.testing.assert_close(actual,expected,atol=tol,rtol=tol)
                for a,e in zip(ag,eg): torch.testing.assert_close(a,e,atol=tol,rtol=tol)
                with torch.inference_mode():
                    out=layer(x,k,s,padding=1)
                    torch.testing.assert_close(out,expected,atol=tol,rtol=tol)

    def test_mixed_precision_data_net(self):
        from models.converse_usrnet import ConvReverseDataNet
        layer=ConvReverseDataNet().to(DEVICE)
        x=torch.randn(2,64,5,7,device=DEVICE,dtype=torch.float16,requires_grad=True)
        k=torch.rand(2,1,3,3,device=DEVICE,dtype=torch.float32,requires_grad=True)
        out=layer(x,k,2)
        self.assertEqual(out.dtype,x.dtype)
        grads=torch.autograd.grad(out.float().square().mean(),(x,k,layer.alpha))
        self.assertTrue(all(torch.isfinite(g).all() for g in grads))

    def test_usrnet_end_to_end_training(self):
        from models.converse_usrnet import ConverseUSRNet
        py=ConverseUSRNet(num_iterations=2,num_blocks=1,backend="pytorch").to(device=DEVICE,dtype=torch.float64)
        cu=copy.deepcopy(py)
        for layer in cu.modules():
            if hasattr(layer,"backend"): layer.backend="cuda" if DEVICE=="cuda" else "pytorch"
        x=torch.randn(2,3,5,7,device=DEVICE,dtype=torch.float64,requires_grad=True)
        k=torch.rand(2,1,7,7,device=DEVICE,dtype=torch.float64,requires_grad=True)
        expected=py(x,k,2)
        eg=torch.autograd.grad(expected.square().mean(),(x,k,py.kernelnet.fc1.weight,py.d.alpha))
        actual=cu(x,k,2)
        ag=torch.autograd.grad(actual.square().mean(),(x,k,cu.kernelnet.fc1.weight,cu.d.alpha))
        torch.testing.assert_close(actual,expected,atol=2e-9,rtol=2e-9)
        for a,e in zip(ag,eg): torch.testing.assert_close(a,e,atol=2e-8,rtol=2e-8)

    def test_batch_gradcheck(self):
        data=tuple(t.requires_grad_() for t in data_for(2,2,1,h=2,w=3))
        fn=lambda *args: torch.ops.converse2d.forward(*args,2,1e-2,"v7")
        self.assertTrue(torch.autograd.gradcheck(fn,data,fast_mode=True,atol=1e-5,rtol=1e-4))
        self.assertTrue(torch.autograd.gradgradcheck(fn,data,fast_mode=True,atol=1e-5,rtol=1e-4))

    def test_invalid_kernel_batch(self):
        data=data_for(2,3,2)
        with self.assertRaises(RuntimeError): torch.ops.converse2d.forward(*data,2)
        with self.assertRaises(ValueError): converse2d_reference(*data,2)


if __name__=="__main__":
    if "--cpu" in sys.argv:
        DEVICE="cpu"
        sys.argv.remove("--cpu")
    result=unittest.main(exit=False,verbosity=2).result
    METRICS.update(device=DEVICE,tests=result.testsRun,passed=result.wasSuccessful(),
                   failures=len(result.failures),errors=len(result.errors))
    (ROOT/"analysis"/f"combined_correctness_{DEVICE}.json").write_text(json.dumps(METRICS,indent=2),encoding="utf-8")
    sys.exit(not result.wasSuccessful())
